app/Http/routes.php
<?php
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


//Route::get('ajout-film','HomeController@ajoutFilm');

Route::auth();

Route::resource('user', 'ProfileController');


//Route::auth('edit/{id}', 'ProfileController@editProfile');

Route::get('/', 'HomeController@index');

Route::get('confirmation', 'HomeController@confirmation');

Route::resource('film', 'FilmController');

Route::resource('critique', 'CritiqueController');


// route to show the login form
Route::get('login', array('uses' => 'HomeController@showLogin'));

// route to process the form
Route::post('login', array('uses' => 'HomeController@doLogin'));
// Route::get('/modifier-compte', array('uses' => 'ProfileController@showModifierCompte'));
Route::get('/modifier-compte', array('uses' => 'ProfileController@showModifierCompte'));
Route::post('/modifier-compte', array('uses' => 'ProfileController@update'));

Route::post('/etoiles', array('uses' => 'CritiqueController@miseAJour'));


Route::get('auth/logout', 'Auth\AuthController@logout');

Route::get('logout', array('uses' => 'HomeController@doLogout'));

Route::post('/search', ['uses' => 'QueryController@search', 'as' => 'queries.search']);

Route::get('protected', ['middleware' => ['auth', 'admin'], function() {
    return "this page requires that you be logged in and an Admin";
}]);



// Route::resource('queries', 'QueryController');

resources/views/ajout-film.blade.php
<!-- @extends('layouts.app')

@section('titre', 'Ajout-film')

@section('content')

    <h1>Ajouter un film</h1>

    {!! Form::open(['url' => 'film.store', 'files' => true]) !!}

        {!! Form::label('titre','Titre: ') !!}
        {!! Form::text('titre') !!}<br>

        {!! Form::label('annee','Année de production: ') !!}
        {!! Form::text('annee') !!}<br>

        {!! Form::file('image','image: ') !!}
        {!! Form::file('image') !!}<br>

        {!! Form::label('classement','Classement: ') !!}
        {!! Form::text('classement') !!}<br>

        {!! Form::label('duree','Durée (min): ') !!}
        {!! Form::text('duree') !!}<br>

        {!! Form::label('synopsis','Synopsis: ') !!}
        {!! Form::text('synopsis') !!}<br>

        {!! Form::label('acteurs','Acteurs: ') !!}
        {!! Form::text('acteurs') !!}

        <!-- classement (provient de la BD...) -->

        <!-- selon le contexte -->
        {!! Form::submit('Ajouter') !!}
        {!! Form::submit('Modifier') !!}

    {!! Form::close() !!}

    @if (count($errors) > 0)
        <ul style="color:red">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif

@stop

@endsection -->

resources/views/confirmation.blade.php
@extends('layouts.app')

@section('titre', 'Confirmation')

@section('content')

    <h4> le film {{ $film->titre }} à bien été modifié</h4>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/modifier-film.blade.php
@extends('layouts.app')

@section('titre', 'Modifier-film')

@section('content')


    <h1>Modifier un film</h1>


    {!! Form::model($film, ['url' => 'update/'.$film->id]) !!}

    {!! Form::label('titre','Titre: ') !!}
    {!! Form::text('titre') !!}

    {!! Form::label('annee','Année de production: ') !!}
    {!! Form::text('annee') !!}

    {!! Form::label('image','Image:') !!}
    {!! Form::file('image') !!}

    {!! Form::label('id_classement','Classement: ') !!} 
    {!! Form::select('id_classement', $classements, $film->classement) !!}
    <?php var_dump($classements); ?>

    {!! Form::label('duree','Durée: ') !!}
    {!! Form::text('duree') !!}

    {!! Form::label('synopsis','Synopsis: ') !!}
    {!! Form::textarea('synopsis') !!}

    {!! Form::label('acteurs','Acteurs: ') !!}
    {!! Form::text('acteurs') !!}

    {!! Form::submit('Ajouter') !!}

    {!! Form::close() !!}

    @if (count($errors) > 0)
        <ul style="color:red">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif


@stop

resources/views/search.blade.php
@extends('layouts.app')

@section('titre', 'search ')

@section('content')
    <div class="">



        <div class="row">
            @if (empty($films))
                Il n'y a pas de film.
            @endif

            @foreach($films as $film)

                



                <div class="col s12 m7 l4">
                    <div class="card large">
                        <div class="card-image">

                            <img src="img/{{ $film->image }}">
                            <img src="img/film/{{ $film->image }}">

                        </div>
                        <div class="card-content">
                            <span class="card-title">
                                <li>{{ $film->titre }} </li></span>
                            <p><li>{{ $film->synopsis }}</li></p>
                        </div>

                        <div class="card-action">
                            <span><i class="material-icons">star</i></span>
                            <span><i class="material-icons">star</i></span>
                            <span><i class="material-icons">star</i></span>
                            <span><i class="material-icons">star</i></span>
                            <span><i class="material-icons">star</i></span>
                            <a class="waves-effect waves-light btn grey lighten-1 right"{{ link_to_route('film.show', 'Détail', $film->id) }}</a>
                        </div>
                    </div>
                </div>




            @endforeach

        </div>




    </div>
@endsection

resources/views/test.blade.php
@extends('layouts.app')

@section('titre', 'Ajout-film')

@section('content')


<h4>   alokajdnvlsjdfv</h4>

@stop